#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# npm test
# export LASTEST_COMMIT= git rev-parse --short HEAD

# 获取最后一个提交的 SHA 值
LAST_COMMIT_SHA=$(git rev-parse --short HEAD)

# 打印 SHA 值到控制台
echo "Last commit SHA: $LAST_COMMIT_SHA"

exit 0